apiVersion: v1
kind: Service
metadata:
  name: daily-aggregate-ledger-report
spec:
  type: ClusterIP
  selector:
    app: daily-aggregate-ledger-report
  ports:
    - port: 55555
      targetPort: 55555
      protocol: TCP